# Exercise 1: NumPy: Create an array with values ranging from 50 to 100

In [7]:
import numpy as np 

array=np.arange(50,101)

array

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

# Exercise 2: Add a border around an existing array

In [9]:
arr=np.ones((2,3),int)
arr
np.pad(arr,pad_width=1,mode='constant',constant_values=2)

array([[2, 2, 2, 2, 2],
       [2, 1, 1, 1, 2],
       [2, 1, 1, 1, 2],
       [2, 2, 2, 2, 2]])

# Exercise 3: Convert a list and tuple into arrays

In [14]:
ar=[1,2,3,4,5,6,7,8]
n=np.array(ar)
print('array is',n)
tuple=(8,4,6,1,2,3)
m=np.array(tuple).reshape(2,3)
print('tuble is',m)

array is [1 2 3 4 5 6 7 8]
tuble is [[8 4 6]
 [1 2 3]]


# Exercise 4: Convert the values of Centigrade degrees into Fahrenheit degrees

In [9]:
ar=np.array([0,12,45.21,34,99.91])
list=[]
for i in ar:
    fran=(i-32)*(5/9)
    list.append(fran)
print("centigrade value",ar)
print("output value ",list)

centigrade value [ 0.   12.   45.21 34.   99.91]
output value  [-17.77777777777778, -11.11111111111111, 7.3388888888888895, 1.1111111111111112, 37.727777777777774]


# Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [22]:
import sys

lin=np.array([1,2,3],float)
print("length of array",lin.size)
print("element value ",lin[0].nbytes)
print("total bytes consumed",lin.nbytes)


length of array 3
element value  8
total bytes consumed 24


# Exercise 6: Get the unique elements of an array

In [28]:
uniq=np.array([10,10,20,20,30,30])
print("unique element",np.unique(uniq))
uniq1=np.array([[1,1],[2,3]])
print("unique element",np.unique(uniq1))

unique element [10 20 30]
unique element [1 2 3]


# Exercise 7: Change the dimension of an array

In [35]:
pac=np.array([1,2,3,4,5,6,7,8,9])
print("original array ",pac)
pac.shape=(3,3)

print("changed dimension 3 row and 3 column",pac)

original array  [1 2 3 4 5 6 7 8 9]
changed dimension 3 row and 3 column [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [49]:
oned=np.linspace(2.5,6.5,30)

print(oned)


[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


# Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [55]:
twod=np.array([10,20,30])

tod=np.array([40,50,60])

c=np.column_stack((twod,tod))
print(c)


[[10 40]
 [20 50]
 [30 60]]


# Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [61]:
mat=np.zeros((5,5))

rag=np.arange(0,5)

row=mat+rag
print("Row values 0 to 4",row)

Row values 0 to 4 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [71]:
list=[]
for i in range(0,100):
    if (i%3==0 or i%5==0):     
        list.append(i)
print(list)
print("sum of numbers",np.sum(list))

[0, 3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99]
sum of numbers 2318


# Exercise 12: Combine a one and a two dimensional array together and display their elements

In [84]:
a=np.arange(4)
print(a)
b=np.arange(8).reshape(2,4)
print(b)
np.nditer([a,b])

for i,j in np.nditer([a,b]):
    print(f'{i}:{j}')


[0 1 2 3]
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


# Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [98]:
rep=np.array([[0.42436315,0.48558583,0.32924763]
         ,[0.7439979,0.58220701,0.38213418]
         ,[0.5097581,0.34528799,0.1563123 ]])

rep[rep>0.5]=0.5
print("Replace all elements of array with .5 which are greater than .5",rep)   

Replace all elements of array with .5 which are greater than .5 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


# Add a new row to an empty numpy array

In [113]:
emt=np.array([])

print(emt)

emt=np.append(emt,np.array([10,20,30]),axis=0)
c=np.stack((emt,np.array([40,50,60])),axis=0)

print('After adding two arrays',c)

[]
After adding two arrays [[10. 20. 30.]
 [40. 50. 60.]]


# Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis.

In [133]:
arrs=np.array([1,2,3])
ars=np.array([2,3,4])
print(arrs,'\n',ars)
d=np.stack((arrs,ars))
print(d)

ap=arrs.reshape((3,1))
dp=ars.reshape((3,1))


print("Sequence of arrays along a new axis:\n",np.stack((ap,dp)).reshape(6,1))

[1 2 3] 
 [2 3 4]
[[1 2 3]
 [2 3 4]]
Sequence of arrays along a new axis:
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
